name: Backup Database

on:
  schedule:
    - cron: '0 */6 * * *' # tiap 6 jam
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backup Endpoint
        run: curl -X GET https://v3.haruman.me/backup/run?token=$BACKUP_KEY
